//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxOne.Web {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FoxOneTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FoxOneTips() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxOne.Web.FoxOneTips", typeof(FoxOneTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有页面 的本地化字符串。
        /// </summary>
        internal static string AllPage {
            get {
                return ResourceManager.GetString("AllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许删除拥有子部门或部门成员的部门信息 的本地化字符串。
        /// </summary>
        internal static string Can_Not_Delete_Department_With_Children_Or_Member {
            get {
                return ResourceManager.GetString("Can_Not_Delete_Department_With_Children_Or_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件编辑器 的本地化字符串。
        /// </summary>
        internal static string Component_Editor {
            get {
                return ResourceManager.GetString("Component_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件ID：{0} 重复 的本地化字符串。
        /// </summary>
        internal static string Ctrl_Id_Repeat {
            get {
                return ResourceManager.GetString("Ctrl_Id_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件ID：{0} 不存在 的本地化字符串。
        /// </summary>
        internal static string Ctrl_Not_Found {
            get {
                return ResourceManager.GetString("Ctrl_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源返回0行数据 的本地化字符串。
        /// </summary>
        internal static string DataSource_Return_Empty {
            get {
                return ResourceManager.GetString("DataSource_Return_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称已存在 的本地化字符串。
        /// </summary>
        internal static string Department_Name_Already_In_Use {
            get {
                return ResourceManager.GetString("Department_Name_Already_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在部门ID为：&apos;{0}&apos;  的部门信息 的本地化字符串。
        /// </summary>
        internal static string Department_Not_Found {
            get {
                return ResourceManager.GetString("Department_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法操作 的本地化字符串。
        /// </summary>
        internal static string InValid_Operation {
            get {
                return ResourceManager.GetString("InValid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始密码错误 的本地化字符串。
        /// </summary>
        internal static string Invalid_Original_Password {
            get {
                return ResourceManager.GetString("Invalid_Original_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的验证码 的本地化字符串。
        /// </summary>
        internal static string InValid_Phone_ValidCode {
            get {
                return ResourceManager.GetString("InValid_Phone_ValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的用户名或密码 的本地化字符串。
        /// </summary>
        internal static string InValid_User_Or_Password {
            get {
                return ResourceManager.GetString("InValid_User_Or_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号或手机号已存在 的本地化字符串。
        /// </summary>
        internal static string LoginId_Or_MobilePhone_Alerady_Exist {
            get {
                return ResourceManager.GetString("LoginId_Or_MobilePhone_Alerady_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登 录 的本地化字符串。
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要为控件：{0} 指定数据源 的本地化字符串。
        /// </summary>
        internal static string Need_DataSource {
            get {
                return ResourceManager.GetString("Need_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件：{0} 需要继承自NoPagerListControlBase 的本地化字符串。
        /// </summary>
        internal static string Need_To_Be_NoPagerListControlBase {
            get {
                return ResourceManager.GetString("Need_To_Be_NoPagerListControlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件：{0} 不是Tree控件 的本地化字符串。
        /// </summary>
        internal static string Need_To_Be_Tree {
            get {
                return ResourceManager.GetString("Need_To_Be_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码与确认密码不一致 的本地化字符串。
        /// </summary>
        internal static string NewPassword_NotEqual_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewPassword_NotEqual_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前操作只支持Table组件 的本地化字符串。
        /// </summary>
        internal static string Only_Suppost_Table_Ctrl {
            get {
                return ResourceManager.GetString("Only_Suppost_Table_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数：&apos;{0}&apos; 不能为空 的本地化字符串。
        /// </summary>
        internal static string Parameter_Not_Found {
            get {
                return ResourceManager.GetString("Parameter_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&apos;{0}&apos;不能为空 的本地化字符串。
        /// </summary>
        internal static string Parameter_Not_Null {
            get {
                return ResourceManager.GetString("Parameter_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string PassWord_Required {
            get {
                return ResourceManager.GetString("PassWord_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号不存在 的本地化字符串。
        /// </summary>
        internal static string Phone_Not_Exist {
            get {
                return ResourceManager.GetString("Phone_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该角色已存在！ 的本地化字符串。
        /// </summary>
        internal static string Role_Alerady_Exist {
            get {
                return ResourceManager.GetString("Role_Alerady_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlId：&apos;{0}&apos; 不存在 的本地化字符串。
        /// </summary>
        internal static string SqlId_Not_Found {
            get {
                return ResourceManager.GetString("SqlId_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统：&apos;{0}&apos;  不存在 的本地化字符串。
        /// </summary>
        internal static string System_Not_Found {
            get {
                return ResourceManager.GetString("System_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 树型菜单 的本地化字符串。
        /// </summary>
        internal static string TreeMenu {
            get {
                return ResourceManager.GetString("TreeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定用户没有下属员工 的本地化字符串。
        /// </summary>
        internal static string User_Is_Not_Supervisor {
            get {
                return ResourceManager.GetString("User_Is_Not_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string User_Name_Required {
            get {
                return ResourceManager.GetString("User_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在用户标识为：&apos;{0}&apos;  的用户信息 的本地化字符串。
        /// </summary>
        internal static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
